// Register
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

// Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

// Logout
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// Account
export const GET_BALANCE_REQUEST = 'GET_BALANCE_REQUEST';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAIL = 'GET_BALANCE_FAIL';

export const GET_QRCODE_REQUEST = 'GET_QRCODE_REQUEST';
export const GET_QRCODE_SUCCESS = 'GET_QRCODE_SUCCESS';
export const GET_QRCODE_FAIL = 'GET_QRCODE_FAIL';

export const SET_PASSWORD_REQUEST = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAIL = 'SET_PASSWORD_FAIL';

export const SET_CURRENT_USER = 'SET_CURRENT_USER'
// Transaction
export const GET_DEPOSIT_TRANSATION_REQUEST = 'GET_DEPOSIT_TRANSATION_REQUEST';
export const GET_DEPOSIT_TRANSATION_SUCCESS = 'GET_DEPOSIT_TRANSATION_SUCCESS';
export const GET_DEPOSIT_TRANSATION_FAIL = 'GET_DEPOSIT_TRANSATION_REQUEST';

export const CREATE_DEPOSIT_FUNDS_REQUEST = 'CREATE_DEPOSIT_FUNDS_REQUEST';
export const CREATE_DEPOSIT_FUNDS_SUCCESS = 'CREATE_DEPOSIT_FUNDS_SUCCESS';
export const CREATE_DEPOSIT_FUNDS_FAIL = 'CREATE_DEPOSIT_FUNDS_FAIL';

export const CREATE_WITHDRAW_FUNDS_REQUEST = 'CREATE_WITHDRAW_FUNDS_REQUEST';
export const CREATE_WITHDRAW_FUNDS_SUCCESS = 'CREATE_WITHDRAW_FUNDS_SUCCESS';
export const CREATE_WITHDRAW_FUNDS_FAIL = 'CREATE_WITHDRAW_FUNDS_FAIL';

export const GET_COMPANY_WITHDRAW_REQUEST = 'GET_COMPANY_WITHDRAW_REQUEST';
export const GET_COMPANY_WITHDRAW_SUCCESS = 'GET_COMPANY_WITHDRAW_SUCCESS';
export const GET_COMPANY_WITHDRAW_FAIL = 'GET_COMPANY_WITHDRAW_FAIL';

export const GET_DEPOSIT_HISTORY_REQUEST = 'GET_DEPOSIT_HISTORY_REQUEST';
export const GET_DEPOSIT_HISTORY_SUCCESS = 'GET_DEPOSIT_HISTORY_SUCCESS';
export const GET_DEPOSIT_HISTORY_FAIL = 'GET_DEPOSIT_HISTORY_FAIL';

export const GET_WITHDRAW_HISTORY_REQUEST = 'GET_WITHDRAW_HISTORY_REQUEST';
export const GET_WITHDRAW_HISTORY_SUCCESS = 'GET_WITHDRAW_HISTORY_SUCCESS';
export const GET_WITHDRAW_HISTORY_FAIL = 'GET_WITHDRAW_HISTORY_FAIL';

export const GET_ARBITRAGE_DETAILS_REQUEST = 'GET_ARBITRAGE_DETAILS_REQUEST';
export const GET_ARBITRAGE_DETAILS_SUCCESS = 'GET_ARBITRAGE_DETAILS_SUCCESS';
export const GET_ARBITRAGE_DETAILS_FAIL = 'GET_ARBITRAGE_DETAILS_FAIL';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

// Manage
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_PLATFORM_REQUEST = 'GET_PLATFORM_REQUEST';
export const GET_PLATFORM_SUCCESS = 'GET_PLATFORM_SUCCESS';
export const GET_PLATFORM_FAIL = 'GET_PLATFORM_FAIL';

export const GET_PROFITS_REQUEST = 'GET_PROFITS_REQUEST';
export const GET_PROFITS_SUCCESS = 'GET_PROFITS_SUCCESS';
export const GET_PROFITS_FAIL = 'GET_PROFITS_FAIL';

export const GET_WITHDRAWS_REQUEST = 'GET_WITHDRAWS_REQUEST';
export const GET_WITHDRAWS_SUCCESS = 'GET_WITHDRAWS_SUCCESS';
export const GET_WITHDRAWS_FAIL = 'GET_WITHDRAWS_FAIL';

export const GET_COMPANY_BALANCE_REQUEST = 'GET_COMPANY_BALANCE_REQUEST';
export const GET_COMPANY_BALANCE_SUCCESS = 'GET_COMPANY_BALANCE_SUCCESS';
export const GET_COMPANY_BALANCE_FAIL = 'GET_COMPANY_BALANCE_FAIL';
// Setting(Mode)
export const SET_MODE_REQUEST = 'SET_MODE_REQUEST';
export const SET_MODE_SUCCESS = 'SET_MODE_SUCCESS';
export const SET_MODE_FAIL = 'SET_MODE_FAIL';

export const GET_COMPANY_ACCOUNT_REQUEST = 'GET_COMPANY_ACCOUNT_REQUEST';
export const GET_COMPANY_ACCOUNT_SUCCESS = 'GET_COMPANY_ACCOUNT_SUCCESS';
export const GET_COMPANY_ACCOUNT_FAIL = 'GET_COMPANY_ACCOUNT_FAIL';

// Referral
export const GET_REFERRAL_INFO_REQUEST = 'GET_REFERRAL_INFO_REQUEST';
export const GET_REFERRAL_INFO_SUCCESS = 'GET_REFERRAL_INFO_SUCCESS';
export const GET_REFERRAL_INFO_FAIL = 'GET_REFERRAL_INFO_FAIL';

export const GET_REFERRAL_USERS_REQUEST = 'GET_REFERRAL_USERS_REQUEST';
export const GET_REFERRAL_USERS_SUCCESS = 'GET_REFERRAL_USERS_SUCCESS';
export const GET_REFERRAL_USERS_FAIL = 'GET_REFERRAL_USERS_FAIL';

export const GET_REFERRAL_TRANSACTIONS_REQUEST = 'GET_REFERRAL_TRANSACTIONS_REQUEST';
export const GET_REFERRAL_TRANSACTIONS_SUCCESS = 'GET_REFERRAL_TRANSACTIONS_SUCCESS';
export const GET_REFERRAL_TRANSACTIONS_FAIL = 'GET_REFERRAL_TRANSACTIONS_FAIL';